### ISSUE TITLE
Unable to construct under IDE

### ISSUE THREAD

**Issue by linmiao233** [wode490390/MultiVersionProxy#3]
Failed to execute goal on project multiversionproxy: Could not resolve dependencies for project cn.wode490390.mcbe:multiversionproxy:jar:1.0.0: Failed to collect dependencies for [com.nukkitx.protocol:bedrock-v361:jar:2.1.2 (compile), com.nukkitx.protocol:bedrock-v354:jar:2.1.2 (compile), com.nukkitx.protocol:bedrock-v340:jar:2.1.2 (compile), com.nukkitx.protocol:bedrock-v332:jar:2.1.2 (compile), com.nukkitx.protocol:bedrock-v313:jar:2.1.2 (compile), com.nukkitx.protocol:bedrock-v291:jar:2.1.2 (compile), org.projectlombok:lombok:jar:1.18.8 (compile), com.google.code.findbugs:jsr305:jar:3.0.2 (compile), com.fasterxml.jackson.core:jackson-databind:jar:2.10.0.pr1 (compile), com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.10.0.pr1 (compile), com.nimbusds:nimbus-jose-jwt:jar:7.9 (compile), org.apache.logging.log4j:log4j-api:jar:2.12.1 (compile), org.apache.logging.log4j:log4j-core:jar:2.12.1 (compile), org.fusesource.jansi:jansi:jar:1.18 (compile), net.sf.jopt-simple:jopt-simple:jar:5.0.4 (compile), net.minecrell:terminalconsoleappender:jar:1.2.0 (compile), org.jline:jline-terminal:jar:3.12.1 (compile), org.jline:jline-terminal-jna:jar:3.12.1 (compile), org.jline:jline-reader:jar:3.12.1 (compile)]: Failed to read artifact descriptor for com.nukkitx.protocol:bedrock-v361:jar:2.1.2: Could not transfer artifact com.nukkitx.protocol:bedrock-v361:pom:2.1.2 from/to nukkitx (http://repo.nukkitx.com/main/): Failed to transfer file: http://repo.nukkitx.com/main/com/nukkitx/protocol/bedrock-v361/2.1.2/bedrock-v361-2.1.2.pom. Return code is: 502 , ReasonPhrase:Bad Gateway. -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by wode490390** [comment]
repo.nukkitx.com is down
